// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PS.Web.API.Data;

namespace PS.Web.API.Migrations
{
    [DbContext(typeof(PolysenseContext))]
    [Migration("20201130195418_ScraperTextCheck")]
    partial class ScraperTextCheck
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PS.Shared.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CongressionalCommitteId")
                        .HasColumnType("int");

                    b.Property<int?>("HouseOfRepresentativesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IntroductionDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("SenateId")
                        .HasColumnType("int");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CongressionalCommitteId");

                    b.HasIndex("HouseOfRepresentativesId");

                    b.HasIndex("SenateId");

                    b.HasIndex("SponsorId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("PS.Shared.Models.BillStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransitionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillStatus");
                });

            modelBuilder.Entity("PS.Shared.Models.Congress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CurrentCongress")
                        .HasColumnType("int");

                    b.Property<int?>("HouseId")
                        .HasColumnType("int");

                    b.Property<int?>("SenateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("SenateId");

                    b.ToTable("Congress");
                });

            modelBuilder.Entity("PS.Shared.Models.CongressionalCommitte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ChairId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChairId");

                    b.ToTable("CongressionalCommitte");
                });

            modelBuilder.Entity("PS.Shared.Models.HouseOfRepresentatives", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("SpeakerOfTheHouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeakerOfTheHouseId");

                    b.ToTable("HouseOfRepresentatives");
                });

            modelBuilder.Entity("PS.Shared.Models.Judge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Judge");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Judge");
                });

            modelBuilder.Entity("PS.Shared.Models.Politician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CongressionalCommitteId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentOffice")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HouseOfRepresentativesId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("SenateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CongressionalCommitteId");

                    b.HasIndex("HouseOfRepresentativesId");

                    b.HasIndex("SenateId");

                    b.ToTable("Politician");
                });

            modelBuilder.Entity("PS.Shared.Models.ScraperText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScraperText");
                });

            modelBuilder.Entity("PS.Shared.Models.Senate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("PresidentOfTheSenateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PresidentOfTheSenateId");

                    b.ToTable("Senate");
                });

            modelBuilder.Entity("PS.Shared.Models.SupremeCourt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ChiefJusticeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransitionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransitionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiefJusticeId");

                    b.ToTable("SupremeCourt");
                });

            modelBuilder.Entity("PS.Shared.Models.Justice", b =>
                {
                    b.HasBaseType("PS.Shared.Models.Judge");

                    b.Property<int?>("AppointedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SupremeCourtId")
                        .HasColumnType("int");

                    b.HasIndex("AppointedById");

                    b.HasIndex("SupremeCourtId");

                    b.HasDiscriminator().HasValue("Justice");
                });

            modelBuilder.Entity("PS.Shared.Models.Bill", b =>
                {
                    b.HasOne("PS.Shared.Models.CongressionalCommitte", null)
                        .WithMany("ProposedBills")
                        .HasForeignKey("CongressionalCommitteId");

                    b.HasOne("PS.Shared.Models.HouseOfRepresentatives", null)
                        .WithMany("Bills")
                        .HasForeignKey("HouseOfRepresentativesId");

                    b.HasOne("PS.Shared.Models.Senate", null)
                        .WithMany("Bills")
                        .HasForeignKey("SenateId");

                    b.HasOne("PS.Shared.Models.Politician", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("PS.Shared.Models.BillStatus", b =>
                {
                    b.HasOne("PS.Shared.Models.Bill", "Bill")
                        .WithMany("HistoricalStatuses")
                        .HasForeignKey("BillId");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("PS.Shared.Models.Congress", b =>
                {
                    b.HasOne("PS.Shared.Models.HouseOfRepresentatives", "House")
                        .WithMany()
                        .HasForeignKey("HouseId");

                    b.HasOne("PS.Shared.Models.Senate", "Senate")
                        .WithMany()
                        .HasForeignKey("SenateId");

                    b.Navigation("House");

                    b.Navigation("Senate");
                });

            modelBuilder.Entity("PS.Shared.Models.CongressionalCommitte", b =>
                {
                    b.HasOne("PS.Shared.Models.Politician", "Chair")
                        .WithMany()
                        .HasForeignKey("ChairId");

                    b.Navigation("Chair");
                });

            modelBuilder.Entity("PS.Shared.Models.HouseOfRepresentatives", b =>
                {
                    b.HasOne("PS.Shared.Models.Politician", "SpeakerOfTheHouse")
                        .WithMany()
                        .HasForeignKey("SpeakerOfTheHouseId");

                    b.Navigation("SpeakerOfTheHouse");
                });

            modelBuilder.Entity("PS.Shared.Models.Politician", b =>
                {
                    b.HasOne("PS.Shared.Models.Bill", null)
                        .WithMany("Cosponsors")
                        .HasForeignKey("BillId");

                    b.HasOne("PS.Shared.Models.CongressionalCommitte", null)
                        .WithMany("Members")
                        .HasForeignKey("CongressionalCommitteId");

                    b.HasOne("PS.Shared.Models.HouseOfRepresentatives", null)
                        .WithMany("CongressMen")
                        .HasForeignKey("HouseOfRepresentativesId");

                    b.HasOne("PS.Shared.Models.Senate", null)
                        .WithMany("Senators")
                        .HasForeignKey("SenateId");
                });

            modelBuilder.Entity("PS.Shared.Models.Senate", b =>
                {
                    b.HasOne("PS.Shared.Models.Politician", "PresidentOfTheSenate")
                        .WithMany()
                        .HasForeignKey("PresidentOfTheSenateId");

                    b.Navigation("PresidentOfTheSenate");
                });

            modelBuilder.Entity("PS.Shared.Models.SupremeCourt", b =>
                {
                    b.HasOne("PS.Shared.Models.Justice", "ChiefJustice")
                        .WithMany()
                        .HasForeignKey("ChiefJusticeId");

                    b.Navigation("ChiefJustice");
                });

            modelBuilder.Entity("PS.Shared.Models.Justice", b =>
                {
                    b.HasOne("PS.Shared.Models.Politician", "AppointedBy")
                        .WithMany()
                        .HasForeignKey("AppointedById");

                    b.HasOne("PS.Shared.Models.SupremeCourt", null)
                        .WithMany("Justices")
                        .HasForeignKey("SupremeCourtId");

                    b.Navigation("AppointedBy");
                });

            modelBuilder.Entity("PS.Shared.Models.Bill", b =>
                {
                    b.Navigation("Cosponsors");

                    b.Navigation("HistoricalStatuses");
                });

            modelBuilder.Entity("PS.Shared.Models.CongressionalCommitte", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("ProposedBills");
                });

            modelBuilder.Entity("PS.Shared.Models.HouseOfRepresentatives", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("CongressMen");
                });

            modelBuilder.Entity("PS.Shared.Models.Senate", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Senators");
                });

            modelBuilder.Entity("PS.Shared.Models.SupremeCourt", b =>
                {
                    b.Navigation("Justices");
                });
#pragma warning restore 612, 618
        }
    }
}
