name: .NET Core

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore PS.Web.API.csproj
    - name: Build
      run: dotnet build PS.Web.API.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test PS.Web.API.csproj --no-restore --verbosity normal
